name: Lacework IaC Scan
# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events but only for the "main" branch
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

        # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-24.04
        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
          # Checks-outs your repository under $GITHUB_WORKSPACE, so your job can access it
          - name: Checkout Code
            uses: actions/checkout@v4

          - name: Install Lacework CLI
            run: |
                # Download and install the Lacework CLI using a shell script 
                curl https://raw.githubusercontent.com/lacework/go-sdk/main/cli/install.sh | bash 
                # Configure the Lacework CLI with account, API key, and secret from GitHub secrets 
                lacework configure -a ${{ secrets.LW_ACCOUNT }}.lacework.net -k ${{ secrets.LW_API_KEY }} -s ${{ secrets.LW_API_SECRET }} --noninteractive 
                # Install the IaC component 
                lacework component install iac 

          - name: Scan the repo for vulnerabilities in IaC
            run: |
                lacework iac scan --directory=. --upload
